// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaCrudColegio.Infrastructure;

#nullable disable

namespace PruebaCrudColegio.Infrastructure.Migrations
{
    [DbContext(typeof(PruebaCrudColegioContext))]
    partial class PruebaCrudColegioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaCrudColegio.Core.Model.College", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9cbea81b-aada-4f31-8250-467bb3a5c0aa"),
                            Address = "Tucuman 868",
                            DateCreated = new DateTimeOffset(new DateTime(2024, 8, 24, 2, 52, 54, 714, DateTimeKind.Unspecified).AddTicks(4768), new TimeSpan(0, -3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Normal",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("PruebaCrudColegio.Core.Model.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0327b17-49d7-499f-97e1-cfd28df1b094"),
                            CollegeId = new Guid("9cbea81b-aada-4f31-8250-467bb3a5c0aa"),
                            DateCreated = new DateTimeOffset(new DateTime(2024, 8, 24, 2, 52, 54, 714, DateTimeKind.Unspecified).AddTicks(4811), new TimeSpan(0, -3, 0, 0, 0)),
                            FirstName = "Alejandro",
                            IsDeleted = false,
                            LastName = "Lopez",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("PruebaCrudColegio.Core.Model.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8354da23-5f45-4080-a999-aa86bdf52b53"),
                            CollegeId = new Guid("9cbea81b-aada-4f31-8250-467bb3a5c0aa"),
                            DateCreated = new DateTimeOffset(new DateTime(2024, 8, 24, 2, 52, 54, 714, DateTimeKind.Unspecified).AddTicks(4814), new TimeSpan(0, -3, 0, 0, 0)),
                            FirstName = "Lisandro",
                            IsDeleted = false,
                            LastName = "Test Description",
                            ProfessorId = new Guid("a0327b17-49d7-499f-97e1-cfd28df1b094"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("PruebaCrudColegio.Core.Model.Professor", b =>
                {
                    b.HasOne("PruebaCrudColegio.Core.Model.College", "College")
                        .WithMany("Professors")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("PruebaCrudColegio.Core.Model.Student", b =>
                {
                    b.HasOne("PruebaCrudColegio.Core.Model.College", "College")
                        .WithMany("Students")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PruebaCrudColegio.Core.Model.Professor", "Professor")
                        .WithMany("Students")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("PruebaCrudColegio.Core.Model.College", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("PruebaCrudColegio.Core.Model.Professor", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
